#ifndef _ASM_ERRNO_H
#define _ASM_ERRNO_H

#include <vmm_error.h>

#define EFAIL           -(VMM_ERR_FAIL)
#define EBUSY           -(VMM_ERR_BUSY)
#define EUNKNOWN        -(VMM_ERR_UNKNOWN)
#define EINVAL          -(VMM_ERR_INVALID)
#define ENOTAVAIL       -(VMM_ERR_NOTAVAIL)
#define EEXIST          -(VMM_ERR_EXIST)
#define EALREADY        -(VMM_ERR_ALREADY)
#define EINVALID        -(VMM_ERR_INVALID)
#define EOVERFLOW       -(VMM_ERR_OVERFLOW)
#define ENOMEM          -(VMM_ERR_NOMEM)
#define ENODEV          -(VMM_ERR_NODEV)
#define ETIMEDOUT       -(VMM_ERR_TIMEDOUT)
#define EIO             -(VMM_ERR_IO)
#define ETIME           -(VMM_ERR_TIME)
#define ENOENT          -(VMM_ERR_NOENT)
#define ERANGE          -(VMM_ERR_RANGE)
#define EILSEQ          -(VMM_ERR_ILSEQ)
#define EOPNOTSUPP      -(VMM_ERR_OPNOTSUPP)
#define EFAULT          -(VMM_ERR_FAULT)
#define ENOSYS          -(VMM_ERR_NOSYS)
#define ENOSPC          -(VMM_ERR_NOSPC)
#define ENODATA         -(VMM_ERR_NODATA)
#define ENXIO           -(VMM_ERR_NXIO)
#define EPROTONOSUPPORT -(VMM_ERR_PROTONOSUPPORT)
#define ESHUTDOWN       -(VMM_ERR_SHUTDOWN)
#define EROFS           -(VMM_ERR_ROFS)
#define EUCLEAN         -(VMM_ERR_UCLEAN)
#define EBADMSG         -(VMM_ERR_BADMSG)
#define EREMOTEIO       -(VMM_ERR_REMOTEIO)
#define EINPROGRESS     -(VMM_ERR_INPROGRESS)
#define E2BIG           -(VMM_ERR_INVALID)
#define ENOTTY          -(VMM_ERR_NODEV)
#define EAGAIN          -(VMM_ERR_AGAIN)
#define EPROTO          -(VMM_ERR_PROTO)
#define EACCES          -(VMM_ERR_ACCESS)
#endif /* defined(_ASM_ERRNO_H) */
